config/routes.rb
if Gem::Version.new("3.0") > Gem::Version.new(Rails.version) then
  #Redmine 1.x
  ActionController::Routing::Routes.draw do |map|
    map.connect 'attachments/download_inline/:id/:filename', :controller => 'attachments', :action => 'download_inline', :id => /\d+/, :filename => /.*/
  end

else
  #Redmine 2.x
  RedmineApp::Application.routes.draw do
    get 'attachments/download_inline/:id/:filename', :controller => 'attachments', :action => 'download_inline', :id => /\d+/, :filename => /.*/
  end
end

app/views/attachments/_links.html.erb
<div class="attachments">

<div class="contextual">
  <%= link_to(l(:label_edit_attachments),
              container_attachments_edit_path(container),
              :title => l(:label_edit_attachments),
              :class => 'icon-only icon-edit'
             ) if options[:editable] %>
</div>

<table>
<% for attachment in attachments %>
<tr>
  <td>
    <% if attachment.is_image? %>
      <%= link_to_attachment attachment, :class => 'icon icon-attachment lightbox_preview', :download => true -%>
      </td>
      <td class="alignrigth">
      <%= link_to l(:button_view),
                  { :controller => 'attachments', :action => 'download', :id => attachment, :filename => attachment.filename },
                  :class => 'icon-only icon-magnifier lightbox_preview ' + attachment.filename.split('.').last.downcase,
                  :rel => 'attachments', :title => "#{attachment.filename}#{ (' - ' + attachment.description) unless attachment.description.blank? }",
                  :data  => {
                    :type => 'image',
                    :fancybox => 'attachments',
                    :caption => "#{attachment.filename}#{ (' - ' + attachment.description) unless attachment.description.blank? }"
                  } %>

    <% elsif attachment.is_pdf? %>
      <%= link_to_attachment attachment, :class => 'icon icon-attachment lightbox_preview pdf', :download => true -%>
      </td>
      <td class="alignrigth">
      <%= link_to l(:button_view),
                  { :controller => 'attachments', :action => 'download_inline', :id => attachment, :filename => attachment.filename },
                  :class => 'icon-only icon-magnifier lightbox_preview pdf',
                  :rel => 'attachments', :title => "#{attachment.filename}#{ (' - ' + attachment.description) unless attachment.description.blank? }",
                  :data  => {
                    :type => 'iframe',
                    :fancybox => 'attachments',
                    :caption => "#{attachment.filename}#{ (' - ' + attachment.description) unless attachment.description.blank? }"
                  } %>

    <% else %>
      <%= link_to_attachment attachment, :class => 'icon icon-attachment' -%>
      </td>
      <td class="alignrigth">
    <% end %>
    <%= link_to_attachment attachment, class: 'icon-only icon-download', title: l(:button_download), download: true -%>
  </td>
  <td class="alignrigth">
    <span class="size"><%= number_to_human_size attachment.filesize %></span>
  </td>
  <td><%= attachment.description unless attachment.description.blank? %></td>
  <td>
    <% if options[:author] %>
      <span class="author"><%= attachment.author %>, <%= format_time(attachment.created_on) %></span>
    <% end %>
  </td>
  <td>
    <% if options[:deletable] %>
      <%= link_to l(:button_delete), attachment_path(attachment),
                  :data => {:confirm => l(:text_are_you_sure)},
                  :method => :delete,
                  :class => 'delete icon-only icon-del',
                  :title => l(:button_delete) %>
    <% end %>
  </td>
</tr>
<% end %>
</table>

<% if defined?(thumbnails) && thumbnails %>
  <% images = attachments.select(&:thumbnailable?) %>
  <% if images.any? %>
  <div class="thumbnails images">
    <% images.each do |attachment| %>
      <div>
        <%=
          link_to image_tag(url_for(:controller => 'attachments', :action => 'thumbnail', :id => attachment)),
          { :controller => 'attachments', :action => 'download', :id => attachment, :filename => attachment.filename },
          :class => ('lightbox' + (attachment.is_pdf? ? ' pdf' : '')) , :rel => 'thumbnails', :title => "#{attachment.filename}#{ ('-' + attachment.description) unless attachment.description.blank? }",
          :data  => {
            :type => attachment.is_pdf? ? 'iframe' : 'image',
            :fancybox => 'thumbnails',
            :caption => "#{attachment.filename}#{ (' - ' + attachment.description) unless attachment.description.blank? }"
          }
        %>
      </div>
    <% end %>
  </div>
  <% end %>
<% else %>
  <% images = attachments.select { |a| a.image? } %>
  <% unless images.empty? %>
    <div class='images'>
      <% images.each do |attachment| %>
        <%= link_to image_tag(url_for({:controller => 'attachments', :action => 'download', :id => attachment, :filename => attachment.filename }), :width => Setting.thumbnails_size),
          { :controller => 'attachments', :action => 'download', :id => attachment, :filename => attachment.filename },
          :class => 'lightbox', :rel => 'thumbnails', :title => "#{attachment.filename}#{ ('-' + attachment.description) unless attachment.description.blank? }",
          :data  => {
            :type => attachment.is_pdf? ? 'iframe' : 'image',
            :fancybox => 'thumbnails',
            :caption => "#{attachment.filename}#{ (' - ' + attachment.description) unless attachment.description.blank? }"
          }
        %>
      <% end -%>
    </div>
  <% end -%>
<% end %>

</div>